from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from ..collision.risk_assessment import compute_pc
from ..decision.cola import avoidance_dv_eci, rtn_axes, rtn_to_eci
from ..physics.propagator import eci_derivative_batch
from ..physics.rk4 import rk4_step_batch
from ..utils.constants import (
    COLLISION_THRESHOLD_KM,
    DEFAULT_DRY_MASS_KG,
    DEFAULT_PROPELLANT_KG,
    G0_M_S2,
    MAX_DV_M_S,
    m_s_to_km_s,
)
from ..utils.math_utils import norm, unit

# ── Scoring weights ───────────────────────────────────────────────────────────
# Tuned for LEO collision avoidance: risk reduction is paramount,
# fuel cost is secondary, orbit deviation is a soft constraint.
W_RISK_REDUCTION  = 10.0   # reward for reducing Pc
W_FUEL_COST       =  1.0   # penalty per m/s of ΔV
W_ORBIT_DEVIATION =  0.5   # penalty for altitude change (km)

# Candidate ΔV magnitudes to evaluate (m/s)
_DV_CANDIDATES_M_S = [1.0, 3.0, 5.0, 8.0, 12.0, MAX_DV_M_S]

# Candidate directions: base avoidance + small rotations in RTN plane
_ANGLE_OFFSETS_DEG = [0.0, 15.0, -15.0, 30.0, -30.0]


@dataclass
class ScoredManeuver:
    """A candidate maneuver with its multi-objective score and reasoning."""
    dv_km_s:          np.ndarray   # ΔV vector in km/s (ECI)
    dv_mag_m_s:       float        # magnitude in m/s
    score:            float        # higher = better
    pc_before:        float        # Pc before maneuver
    pc_after:         float        # Pc after maneuver
    risk_reduction:   float        # pc_before - pc_after
    fuel_cost_m_s:    float        # ΔV magnitude (m/s)
    orbit_deviation_km: float      # change in orbital radius (km)
    reasoning:        str          # human-readable explanation


def _orbit_deviation(state_before: np.ndarray, state_after: np.ndarray) -> float:
    """Change in orbital radius after applying ΔV (km)."""
    r_before = norm(state_before[0:3])
    r_after  = norm(state_after[0:3])
    return abs(r_after - r_before)


def _apply_dv(state: np.ndarray, dv_km_s: np.ndarray) -> np.ndarray:
    """Return a new state with ΔV applied to velocity."""
    new_state = state.copy()
    new_state[3:6] += dv_km_s
    return new_state


def _pc_after_maneuver(
    state_sat_post: np.ndarray,
    state_threat:   np.ndarray,
    lookahead_s:    float = 300.0,
) -> float:
    """
    Estimate Pc after a maneuver by propagating both objects forward
    `lookahead_s` seconds and computing Pc at the resulting states.
    """
    states = np.stack([state_sat_post, state_threat], axis=0)
    propagated = rk4_step_batch(states, lookahead_s, eci_derivative_batch)

    dr     = propagated[0, 0:3] - propagated[1, 0:3]
    dv_rel = propagated[0, 3:6] - propagated[1, 3:6]
    miss   = norm(dr)

    return compute_pc(miss, dv_rel, dr)


def score_maneuver(
    dv_km_s:      np.ndarray,
    state_sat:    np.ndarray,
    state_threat: np.ndarray,
    pc_before:    float,
) -> ScoredManeuver:
    """Evaluate a single candidate ΔV and return its scored result."""
    dv_mag_m_s = norm(dv_km_s) * 1000.0
    state_post = _apply_dv(state_sat, dv_km_s)

    pc_after   = _pc_after_maneuver(state_post, state_threat)
    risk_red   = max(0.0, pc_before - pc_after)
    orbit_dev  = _orbit_deviation(state_sat, state_post)

    score = (
        W_RISK_REDUCTION  * risk_red
        - W_FUEL_COST       * dv_mag_m_s
        - W_ORBIT_DEVIATION * orbit_dev
    )

    reasoning = (
        f"ΔV={dv_mag_m_s:.1f} m/s | "
        f"Pc {pc_before:.2e}→{pc_after:.2e} | "
        f"risk↓{risk_red:.2e} | "
        f"orbit dev {orbit_dev:.2f} km | "
        f"score={score:.4f}"
    )

    return ScoredManeuver(
        dv_km_s=dv_km_s,
        dv_mag_m_s=dv_mag_m_s,
        score=score,
        pc_before=pc_before,
        pc_after=pc_after,
        risk_reduction=risk_red,
        fuel_cost_m_s=dv_mag_m_s,
        orbit_deviation_km=orbit_dev,
        reasoning=reasoning,
    )


def optimise_maneuver(
    state_sat:    np.ndarray,
    state_threat: np.ndarray,
    pc_before:    float,
) -> ScoredManeuver | None:
    """
    Generate multiple candidate ΔV vectors, score each on:
      score = W_RISK * risk_reduction - W_FUEL * dv_mag - W_ORBIT * orbit_dev

    Returns the highest-scoring candidate, or None if no candidate
    improves Pc above a minimum threshold.

    Candidates are generated by:
      - Multiple ΔV magnitudes (1–15 m/s)
      - Base avoidance direction (RTN geometry-aware)
      - Small angular rotations of the base direction in the orbital plane
    """
    r_sat = state_sat[0:3]
    v_sat = state_sat[3:6]
    r_hat, t_hat, n_hat = rtn_axes(r_sat, v_sat)

    # Base avoidance direction (unit vector in ECI)
    base_dv_unit = unit(avoidance_dv_eci(state_sat, state_threat, 1.0))

    candidates: list[ScoredManeuver] = []

    for dv_m_s in _DV_CANDIDATES_M_S:
        dv_km_s_mag = m_s_to_km_s(dv_m_s)

        for angle_deg in _ANGLE_OFFSETS_DEG:
            # Rotate base direction in the RT plane by angle_deg
            angle_rad = angle_deg * (np.pi / 180.0)
            cos_a, sin_a = np.cos(angle_rad), np.sin(angle_rad)

            # Express base direction in RTN
            base_r = np.dot(base_dv_unit, r_hat)
            base_t = np.dot(base_dv_unit, t_hat)

            # Rotate in RT plane
            rot_r = cos_a * base_r - sin_a * base_t
            rot_t = sin_a * base_r + cos_a * base_t

            # Back to ECI (keep normal component zero)
            dv_eci = (rot_r * r_hat + rot_t * t_hat) * dv_km_s_mag

            result = score_maneuver(dv_eci, state_sat, state_threat, pc_before)
            candidates.append(result)

    if not candidates:
        return None

    best = max(candidates, key=lambda c: c.score)

    # Only return if the maneuver actually improves the situation
    if best.risk_reduction <= 0.0:
        return None

    return best


def plan_optimised_cola(
    collision_pairs,
    states_by_id:             dict[str, np.ndarray],
    last_maneuver_time_by_id: dict[str, float],
    current_time_s:           float,
    object_records:           dict | None = None,
) -> dict[str, tuple[np.ndarray, ScoredManeuver]]:
    """
    Drop-in replacement for plan_cola_maneuvers that uses multi-objective
    scoring instead of a fixed formula.

    Returns dict mapping obj_id → (dv_km_s, ScoredManeuver) so callers
    can log the reasoning alongside the burn command.
    """
    from ..utils.constants import MANEUVER_COOLDOWN_S
    from ..decision.cola import COLA_MIN_FUEL_PCT, _fuel_pct

    if not collision_pairs:
        return {}

    result: dict[str, tuple[np.ndarray, ScoredManeuver]] = {}

    for pair in collision_pairs:
        # Cooldown check
        last_a = last_maneuver_time_by_id.get(pair.a)
        last_b = last_maneuver_time_by_id.get(pair.b)
        a_ok = last_a is None or (current_time_s - last_a) >= MANEUVER_COOLDOWN_S
        b_ok = last_b is None or (current_time_s - last_b) >= MANEUVER_COOLDOWN_S

        if not a_ok and not b_ok:
            continue

        # Fuel gate
        if object_records is not None:
            rec_a = object_records.get(pair.a)
            rec_b = object_records.get(pair.b)
            if rec_a and _fuel_pct(rec_a) < COLA_MIN_FUEL_PCT:
                a_ok = False
            if rec_b and _fuel_pct(rec_b) < COLA_MIN_FUEL_PCT:
                b_ok = False

        if not a_ok and not b_ok:
            continue

        state_a = states_by_id.get(pair.a)
        state_b = states_by_id.get(pair.b)
        if state_a is None or state_b is None:
            continue

        pc_before = getattr(pair, "pc", 1e-3)

        # Choose maneuvering object (higher fuel)
        if a_ok and b_ok and object_records is not None:
            rec_a = object_records.get(pair.a)
            rec_b = object_records.get(pair.b)
            fuel_a = _fuel_pct(rec_a) if rec_a else 100.0
            fuel_b = _fuel_pct(rec_b) if rec_b else 100.0
            if fuel_b > fuel_a:
                a_ok = False
            else:
                b_ok = False

        if a_ok:
            best = optimise_maneuver(state_a, state_b, pc_before)
            if best:
                result[pair.a] = (best.dv_km_s, best)

        elif b_ok:
            best = optimise_maneuver(state_b, state_a, pc_before)
            if best:
                result[pair.b] = (best.dv_km_s, best)

    return result
